Repository DukeRobotics/robosub-ros, pull requests merged in 2022-09, with the labels that each got.

#328 Merge task planning changes into master
  landside/catkin_ws/src/simulation/personal/scenes/common_code.lua
  landside/catkin_ws/src/simulation/personal/scenes/robot_code.lua
  landside/catkin_ws/src/simulation/scripts/fake_cv_maker.py
  landside/catkin_ws/src/simulation/scripts/sim_handle.py
  onboard/catkin_ws/src/acoustics/scripts/saleae_interface.py
  onboard/catkin_ws/src/controls/launch/position_pid.launch
  onboard/catkin_ws/src/controls/launch/velocity_pid.launch
  onboard/catkin_ws/src/controls/scripts/test_state_publisher.py
  onboard/catkin_ws/src/cv/launch/stream_images.launch
  onboard/catkin_ws/src/cv/models/models.yaml
  onboard/catkin_ws/src/cv/package.xml
  onboard/catkin_ws/src/cv/scripts/detection.py
  onboard/catkin_ws/src/cv/scripts/stream_images.py
  onboard/catkin_ws/src/cv/scripts/utils.py
  onboard/catkin_ws/src/data_pub/scripts/imu.py
  onboard/catkin_ws/src/task_planning/launch/task_runner.launch
  onboard/catkin_ws/src/task_planning/scripts/buoy_task.py
  onboard/catkin_ws/src/task_planning/scripts/cv_tasks.py
  onboard/catkin_ws/src/task_planning/scripts/gate_pseudo_code.txt
  onboard/catkin_ws/src/task_planning/scripts/gate_task.py
  onboard/catkin_ws/src/task_planning/scripts/move_tasks.py
  onboard/catkin_ws/src/task_planning/scripts/octagon_task.py
  onboard/catkin_ws/src/task_planning/scripts/prequal_task_sm.py
  onboard/catkin_ws/src/task_planning/scripts/prequal_tasks.py
  onboard/catkin_ws/src/task_planning/scripts/smach_concurrence.py
  onboard/catkin_ws/src/task_planning/scripts/smach_concurrent_sm.py
  onboard/catkin_ws/src/task_planning/scripts/smach_test.py
  onboard/catkin_ws/src/task_planning/scripts/style_task.py
  onboard/catkin_ws/src/task_planning/scripts/task.py
  onboard/catkin_ws/src/task_planning/scripts/task_runner.py
  onboard/catkin_ws/src/task_planning/scripts/task_state.py
  onboard/catkin_ws/src/task_planning/scripts/task_utils.py
Labels: task planning

#334 Add Docker image artifacts
  .github/workflows/build-artifacts.yml
  .github/workflows/delete-artifacts.yml
  docker/README.md
Labels: systems

#335 Update Launch dependencies
  docker/onboard/Dockerfile
  onboard/catkin_ws/src/cv/launch/stream_images.launch
  onboard/catkin_ws/src/cv/package.xml
  onboard/catkin_ws/src/cv/scripts/stream_images.py
  onboard/catkin_ws/src/task_planning/CMakeLists.txt
  onboard/catkin_ws/src/task_planning/launch/task_runner.launch
  onboard/catkin_ws/src/task_planning/package.xml
  onboard/catkin_ws/src/task_planning/scripts/move_tasks.py
  onboard/catkin_ws/src/task_planning/scripts/task_runner.py
Labels: systems, task planning, cv

#338 Automate artifact deletion
  .github/workflows/delete-artifacts.yml
Labels: systems

#339 Migrate CI to docker buildx
  .github/workflows/build-artifacts.yml
  .github/workflows/build.sh
  .github/workflows/build.yml
  .github/workflows/daily-build.yml
  .github/workflows/delete-artifacts.yml
  .github/workflows/setup.sh
  docker/core/Dockerfile
Labels: systems
