Repository DukeRobotics/robosub-ros, pull requests merged in 2024-04, with the labels that each got.

#521 Controls layouts
  foxglove/README.md
  foxglove/layouts/controls-power.json
  foxglove/layouts/current-pose.json
  foxglove/layouts/drc.json
  foxglove/layouts/pid-position.json
  foxglove/layouts/pid-velocity.json
  foxglove/layouts/sensors.json
  foxglove/layouts/state.json
  onboard/catkin_ws/src/system_utils/scripts/topic_transforms.py
Labels: gui

#537 Joystick fix
  foxglove/extensions/toggle-joystick-panel/src/ToggleJoystickPanel.tsx
Labels: gui

#538 Sensor Fusion Updates
  onboard/catkin_ws/src/sensor_fusion/params/main.yaml
Labels: Very Important Cool Things

#526 Sonar Distance Algorithm
  core/catkin_ws/src/custom_msgs/CMakeLists.txt
  core/catkin_ws/src/custom_msgs/msg/SonarSweepResponse.msg
  onboard/catkin_ws/src/cv/scripts/depthai_spatial_detection.py
  onboard/catkin_ws/src/sonar/scripts/sampleData/10meterdata.bin
  onboard/catkin_ws/src/sonar/scripts/sampleData/SampleTylerData.bin
  onboard/catkin_ws/src/sonar/scripts/sampleData/Sonar_Image.jpeg
  onboard/catkin_ws/src/sonar/scripts/sampleData/Sonar_Image2.jpeg
  onboard/catkin_ws/src/sonar/scripts/sampleData/Sonar_Image3.jpeg
  onboard/catkin_ws/src/sonar/scripts/sampleData/buoy.npy
  onboard/catkin_ws/src/sonar/scripts/sampleData/gate.npy
  onboard/catkin_ws/src/sonar/scripts/sampleData/gater5.npy
  onboard/catkin_ws/src/sonar/scripts/sonar.py
  onboard/catkin_ws/src/sonar/scripts/sonar_image_processing.py
  onboard/catkin_ws/src/static_transforms/launch/static_transforms.launch
Labels: Very Important Cool Things

#540 Sonar Fixes
  docker/onboard/Dockerfile
  onboard/catkin_ws/src/sonar/scripts/sonar_image_processing.py
Labels: sonar

#541 Fix Windows compatibility with ROS TypeScript generator
  foxglove/foxglove.py
  foxglove/shared/defs/package.json
  foxglove/shared/defs/ros_ts_generator_configs/custom-msgs.json
  foxglove/shared/defs/ros_ts_generator_configs/ros-ts-generator-config.json
Labels: gui

#545 Updated Pressure Arduino Onboard Voltage
  onboard/catkin_ws/src/offboard_comms/Arduino Sketchbooks/PressureArduino/PressureArduino.ino
Labels: electrical
