Repository DukeRobotics/robosub-ros, pull requests merged in 2024-01, with the labels that each got.

#495 Scrollable Extensions
  foxglove/extensions/call-service-panel/src/CallServicePanel.tsx
  foxglove/extensions/publish-topic-panel/src/PublishTopicPanel.tsx
  foxglove/extensions/sensors-status-panel/src/SensorsStatusPanel.tsx
  foxglove/extensions/subscribe-topic-panel/src/SubscribeTopicPanel.tsx
  foxglove/extensions/system-status-panel/src/SystemStatusPanel.tsx
  foxglove/extensions/thruster-speeds-panel/src/ThrusterSpeedsPanel.tsx
  foxglove/extensions/toggle-controls-panel/src/ToggleControlsPanel.tsx
  foxglove/extensions/toggle-joystick-panel/src/ToggleJoystickPanel.tsx
Labels: gui

#496 Foxglove Cleanup
  foxglove/README.md
  foxglove/extensions/call-service-panel/src/CallServicePanel.tsx
  foxglove/extensions/publish-topic-panel/src/PublishTopicPanel.tsx
  foxglove/extensions/sensors-status-panel/src/SensorsStatusPanel.tsx
  foxglove/extensions/subscribe-topic-panel/src/SubscribeTopicPanel.tsx
  foxglove/extensions/system-status-panel/src/SystemStatusPanel.tsx
  foxglove/extensions/thruster-speeds-panel/src/ThrusterSpeedsPanel.tsx
  foxglove/extensions/toggle-controls-panel/src/ToggleControlsPanel.tsx
  foxglove/extensions/toggle-joystick-panel/src/ToggleJoystickPanel.tsx
  foxglove/foxglove.py
Labels: gui

#491 PID Panel
  core/catkin_ws/src/custom_msgs/CMakeLists.txt
  core/catkin_ws/src/custom_msgs/msg/PIDGain.msg
  core/catkin_ws/src/custom_msgs/msg/PIDGains.msg
  core/catkin_ws/src/custom_msgs/srv/SetPIDGains.srv
  foxglove/README.md
  foxglove/extensions/pid-panel/README.md
  foxglove/extensions/pid-panel/package.json
  foxglove/extensions/pid-panel/src/PIDPanel.tsx
  foxglove/extensions/pid-panel/src/index.ts
  foxglove/extensions/pid-panel/tsconfig.json
  foxglove/package-lock.json
Labels: gui

#500 Foxglove Fixes from Jan 13 Pool Test
  foxglove/README.md
  foxglove/empty-layout.json
  foxglove/foxglove.py
  foxglove/layouts/controls-monitor.json
Labels: gui

#501 PID Panel Fix
  foxglove/extensions/pid-panel/src/PIDPanel.tsx
Labels: gui

#504 Update package.json
  foxglove/extensions/call-service-panel/package.json
  foxglove/extensions/pid-panel/package.json
  foxglove/extensions/publish-topic-panel/package.json
  foxglove/extensions/sensors-status-panel/package.json
  foxglove/extensions/subscribe-topic-panel/package.json
  foxglove/extensions/system-status-panel/package.json
  foxglove/extensions/toggle-controls-panel/package.json
  foxglove/extensions/toggle-joystick-panel/package.json
Labels: gui

#505 PID Panel step incrementers
  foxglove/extensions/pid-panel/src/PIDPanel.tsx
Labels: gui

#506 Add foxglove clean
  foxglove/README.md
  foxglove/foxglove.py
Labels: gui

#508 Add current-pose and drc layout
  foxglove/README.md
  foxglove/layouts/current-pose.json
  foxglove/layouts/drc.json
Labels: gui

#509 Pressure Filter
  onboard/catkin_ws/src/data_pub/README.md
  onboard/catkin_ws/src/data_pub/config/pressure_ftdi.yaml
  onboard/catkin_ws/src/data_pub/scripts/pressure.py
  onboard/catkin_ws/src/offboard_comms/scripts/dual_upload.sh
Labels: sensors

#510 Voltage Sensor Integration
  onboard/catkin_ws/src/data_pub/README.md
  onboard/catkin_ws/src/data_pub/config/arduino_ftdi.yaml
  onboard/catkin_ws/src/data_pub/launch/pub_all.launch
  onboard/catkin_ws/src/data_pub/launch/pub_depth.launch
  onboard/catkin_ws/src/data_pub/launch/pub_sensors.launch
  onboard/catkin_ws/src/data_pub/scripts/sensors.py
Labels: Very Important Cool Things

#511 Arduino voltage publishing over serial
  onboard/catkin_ws/src/offboard_comms/Arduino Sketchbooks/PressureArduino/PressureArduino.ino
  onboard/catkin_ws/src/offboard_comms/README.md
Labels: electrical

#512 Foxglove WebSocket Alias
  docker/core/ssh_entry.sh
Labels: gui

#513 Pressure Arduino Bug Fix
  onboard/catkin_ws/src/offboard_comms/Arduino Sketchbooks/PressureArduino/PressureArduino.ino
Labels: electrical

#515 Sonar Overhaul
  core/catkin_ws/src/custom_msgs/CMakeLists.txt
  core/catkin_ws/src/custom_msgs/action/sweep.action
  core/catkin_ws/src/custom_msgs/msg/SonarRequest.msg
  core/catkin_ws/src/custom_msgs/msg/SonarResponse.msg
  core/catkin_ws/src/custom_msgs/msg/SonarSweepRequest.msg
  onboard/catkin_ws/src/cv/scripts/depthai_spatial_detection.py
  onboard/catkin_ws/src/execute/launch/sensors.launch
  onboard/catkin_ws/src/sonar/launch/sonar.launch
  onboard/catkin_ws/src/sonar/scripts/sonar.py
  onboard/catkin_ws/src/sonar/scripts/sonar_image_processing.py
  onboard/catkin_ws/src/sonar/scripts/sonar_pool_test.py
  onboard/catkin_ws/src/sonar/scripts/sonar_publisher.py
  onboard/catkin_ws/src/sonar/scripts/sonar_utils.py
  onboard/catkin_ws/src/sonar/sonar_refactor.mkd
Labels: sonar

#514 Add voltage status to system status panel
  foxglove/extensions/system-status-panel/src/SystemStatusPanel.tsx
Labels: gui

#517 Pressure Fixes
  onboard/catkin_ws/src/data_pub/scripts/sensors.py
  onboard/catkin_ws/src/offboard_comms/scripts/dual_upload.sh
  onboard/catkin_ws/src/offboard_comms/scripts/pressure_port.sh
Labels: electrical
