Repository DukeRobotics/robosub-ros, pull requests merged in 2024-03, with the labels that each got.

#527 add sourcing and aliases to bashrc not bash_profile
  docker/core/Dockerfile
  docker/core/entrypoint.sh
  docker/core/ros_bashrc.sh
  docker/core/ssh_entry.sh
Labels: systems

#533 Remove useless package-lock.json file
  package-lock.json
Labels: Very Important Cool Things

#535 New Robot Fixes
  onboard/catkin_ws/src/offboard_comms/Arduino Sketchbooks/oogwayThrusterOffset.h
  onboard/catkin_ws/src/vectornav/params/vn100.yaml
Labels: electrical

#536 Added ROBOT_NAME to bash_profile
  docker/core/entrypoint.sh
Labels: systems
