Repository DukeRobotics/robosub-ros, pull requests merged in 2024-02, with the labels that each got.

#519 Toggle Controls Panel Fix
  foxglove/extensions/toggle-controls-panel/src/ToggleControlsPanel.tsx
Labels: gui

#520 Docker Fixes
  docker-compose.yml
  docker/onboard/Dockerfile
Labels: systems

#524 Offboard Comms
  .github/workflows/test_arduino.sh
  docker/core/ssh_entry.sh
  onboard/catkin_ws/src/data_pub/README.md
  onboard/catkin_ws/src/data_pub/config/arduino_ftdi.yaml
  onboard/catkin_ws/src/data_pub/config/cthulhu.yaml
  onboard/catkin_ws/src/data_pub/config/cthulhu/dvl.yaml
  onboard/catkin_ws/src/data_pub/config/dvl_ftdi.yaml
  onboard/catkin_ws/src/data_pub/config/oogway.yaml
  onboard/catkin_ws/src/data_pub/config/oogway/dvl.yaml
  onboard/catkin_ws/src/data_pub/scripts/dvl_raw.py
  onboard/catkin_ws/src/data_pub/scripts/dvl_to_odom.py
  onboard/catkin_ws/src/data_pub/scripts/sensors.py
  onboard/catkin_ws/src/offboard_comms/Arduino Sketchbooks/PressureArduino/Adafruit_PWMServoDriver.cpp
  onboard/catkin_ws/src/offboard_comms/Arduino Sketchbooks/PressureArduino/Adafruit_PWMServoDriver.h
  onboard/catkin_ws/src/offboard_comms/Arduino Sketchbooks/PressureArduino/MS5837.cpp
  onboard/catkin_ws/src/offboard_comms/Arduino Sketchbooks/PressureArduino/MS5837.h
  onboard/catkin_ws/src/offboard_comms/Arduino Sketchbooks/PressureArduino/MultiplexedBasicESC.cpp
  onboard/catkin_ws/src/offboard_comms/Arduino Sketchbooks/PressureArduino/MultiplexedBasicESC.h
  onboard/catkin_ws/src/offboard_comms/Arduino Sketchbooks/PressureArduino/MultiplexedServo.cpp
  onboard/catkin_ws/src/offboard_comms/Arduino Sketchbooks/PressureArduino/MultiplexedServo.h
  onboard/catkin_ws/src/offboard_comms/Arduino Sketchbooks/PressureArduino/PressureArduino.ino
  onboard/catkin_ws/src/offboard_comms/Arduino Sketchbooks/ThrusterArduino/MS5837.cpp
  onboard/catkin_ws/src/offboard_comms/Arduino Sketchbooks/ThrusterArduino/MS5837.h
  onboard/catkin_ws/src/offboard_comms/Arduino Sketchbooks/ThrusterArduino/ThrusterArduino.ino
  onboard/catkin_ws/src/offboard_comms/README.md
  onboard/catkin_ws/src/offboard_comms/config/cthulhu.yaml
  onboard/catkin_ws/src/offboard_comms/config/oogway.yaml
  onboard/catkin_ws/src/offboard_comms/launch/serial.launch
  onboard/catkin_ws/src/offboard_comms/scripts/arduino.py
  onboard/catkin_ws/src/offboard_comms/scripts/arduino_upload.sh
  onboard/catkin_ws/src/offboard_comms/scripts/copy_offset.sh
  onboard/catkin_ws/src/offboard_comms/scripts/devices.sh
  onboard/catkin_ws/src/offboard_comms/scripts/dual_upload.sh
  onboard/catkin_ws/src/offboard_comms/scripts/port_finder.sh
  onboard/catkin_ws/src/offboard_comms/scripts/pressure_port.sh
  onboard/catkin_ws/src/offboard_comms/scripts/thruster_port.sh
  onboard/catkin_ws/src/offboard_comms/src/thrusters.cpp
Labels: electrical
